version: '3'

tasks:
  labelify:
    desc: Check that catalogue and all vocabs have labels
    cmds:
      - labelify -c _background/ {{.CLI_ARGS}}
  validate:
    desc: Check that a vocab is valida according to VocPub
    cmds:
      - pyshacl -s _scripts/vocpub-4.10.ttl -w -f table {{.CLI_ARGS}} || true
  tidy:
    desc: Reformat model ttl file
    cmds:
      - python scripts/reformat_ttl.py model.ttl
      - echo "RDF tidied"
  rdf:
    desc: check the validity of an RDF file
    cmds:
      - python _scripts/validate_rdf.py {{.CLI_ARGS}}
